# Generated by Django 5.1.7 on 2025-03-29 12:41

import django.db.models.deletion
import pdf_app.models.document
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to=pdf_app.models.document.document_upload_path, verbose_name='PDF File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('num_pages', models.IntegerField(blank=True, null=True, verbose_name='Number of Pages')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('status', models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('processed', 'Processed'), ('error', 'Error')], default='new', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('x1', models.FloatField(blank=True, null=True, verbose_name='X1 Coordinate')),
                ('y1', models.FloatField(blank=True, null=True, verbose_name='Y1 Coordinate')),
                ('x2', models.FloatField(blank=True, null=True, verbose_name='X2 Coordinate')),
                ('y2', models.FloatField(blank=True, null=True, verbose_name='Y2 Coordinate')),
                ('page', models.IntegerField(default=1, verbose_name='Page Number')),
                ('has_header', models.BooleanField(default=True, verbose_name='Has Header')),
                ('has_borders', models.BooleanField(default=True, verbose_name='Has Borders')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='pdf_app.configuration', verbose_name='Configuration')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['template', 'page'],
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('settings', models.JSONField(blank=True, null=True, verbose_name='Settings')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('code', models.TextField(blank=True, verbose_name='Python Code')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Started At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Status')),
                ('results', models.JSONField(blank=True, null=True, verbose_name='Results')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='pdf_app.configuration', verbose_name='Configuration')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuration_runs', to='pdf_app.document', verbose_name='Document')),
            ],
            options={
                'verbose_name': 'Configuration Run',
                'verbose_name_plural': 'Configuration Runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TableColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('x1', models.FloatField(blank=True, null=True, verbose_name='X1 Coordinate')),
                ('x2', models.FloatField(blank=True, null=True, verbose_name='X2 Coordinate')),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('boolean', 'Boolean')], default='text', max_length=20, verbose_name='Data Type')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('regex_pattern', models.CharField(blank=True, max_length=255, verbose_name='Regex Pattern')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='pdf_app.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Table Column',
                'verbose_name_plural': 'Table Columns',
                'ordering': ['table', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=20, verbose_name='Status')),
                ('is_public', models.BooleanField(default=False, verbose_name='Public Template')),
                ('version', models.IntegerField(default=1, verbose_name='Version')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
                'ordering': ['-updated_at'],
                'permissions': [('can_use_template', 'Can use template'), ('can_share_template', 'Can share template')],
            },
        ),
        migrations.AddField(
            model_name='table',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='pdf_app.template', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('selection', 'Selection')], default='text', max_length=20, verbose_name='Field Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('x1', models.FloatField(blank=True, null=True, verbose_name='X1 Coordinate')),
                ('y1', models.FloatField(blank=True, null=True, verbose_name='Y1 Coordinate')),
                ('x2', models.FloatField(blank=True, null=True, verbose_name='X2 Coordinate')),
                ('y2', models.FloatField(blank=True, null=True, verbose_name='Y2 Coordinate')),
                ('page', models.IntegerField(default=1, verbose_name='Page Number')),
                ('is_required', models.BooleanField(default=False, verbose_name='Required')),
                ('min_length', models.IntegerField(blank=True, null=True, verbose_name='Minimum Length')),
                ('max_length', models.IntegerField(blank=True, null=True, verbose_name='Maximum Length')),
                ('regex_pattern', models.CharField(blank=True, max_length=255, verbose_name='Regex Pattern')),
                ('options', models.JSONField(blank=True, help_text='Options for selection fields', null=True, verbose_name='Options')),
                ('default_value', models.CharField(blank=True, max_length=255, verbose_name='Default Value')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pdf_app.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Field',
                'verbose_name_plural': 'Fields',
                'ordering': ['template', 'order'],
            },
        ),
        migrations.AddField(
            model_name='configuration',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations', to='pdf_app.template', verbose_name='Template'),
        ),
    ]
