# Generated by Django 5.1.7 on 2025-03-29 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='field',
            options={'ordering': ['configuration', 'order'], 'verbose_name': 'Field', 'verbose_name_plural': 'Fields'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['configuration', 'page'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='template',
        ),
        migrations.RemoveField(
            model_name='field',
            name='template',
        ),
        migrations.RemoveField(
            model_name='table',
            name='template',
        ),
        migrations.AddField(
            model_name='field',
            name='configuration',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='pdf_app.configuration', verbose_name='Configuration'),
        ),
    ]
