# Generated by Django 5.1.7 on 2025-03-29 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0004_pythonfunction_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='python_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fields', to='pdf_app.pythonfunction', verbose_name='Python Function'),
        ),
        migrations.AddField(
            model_name='tablecolumn',
            name='python_function',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_columns', to='pdf_app.pythonfunction', verbose_name='Python Function'),
        ),
    ]
