# Generated by Django 5.1.7 on 2025-03-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0006_template_configuration_template_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pythonfunction',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
