# Generated by Django 5.1.7 on 2025-03-30 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0007_alter_pythonfunction_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pythonfunction',
            options={'ordering': ['-updated_at', 'name'], 'verbose_name': 'Python Function', 'verbose_name_plural': 'Python Functions'},
        ),
    ]
