# Generated by Django 5.1.7 on 2025-03-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0008_alter_pythonfunction_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefield',
            name='ocr_required',
            field=models.BooleanField(default=False, verbose_name='OCR Required'),
        ),
    ]
