# Generated by Django 5.1.7 on 2025-03-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0009_templatefield_ocr_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='account_text',
            field=models.CharField(blank=True, max_length=255, verbose_name='Account Text'),
        ),
        migrations.AddField(
            model_name='template',
            name='first_page_height',
            field=models.FloatField(default=0, verbose_name='First Page Height'),
        ),
        migrations.AddField(
            model_name='template',
            name='first_page_width',
            field=models.FloatField(default=0, verbose_name='First Page Width'),
        ),
        migrations.AddField(
            model_name='template',
            name='has_watermarks',
            field=models.BooleanField(default=False, verbose_name='Contains Watermarks'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_multi_account',
            field=models.BooleanField(default=False, verbose_name='Multi Account Statement'),
        ),
        migrations.AddField(
            model_name='template',
            name='unnecessary_page_delta',
            field=models.IntegerField(default=0, verbose_name='Unnecessary Page Delta'),
        ),
        migrations.AddField(
            model_name='template',
            name='unnecessary_page_position',
            field=models.CharField(blank=True, choices=[('first', 'First'), ('last', 'Last')], max_length=5, null=True, verbose_name='Unnecessary Page Position'),
        ),
    ]
