# Generated by Django 5.1.7 on 2025-03-31 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0011_templatefield_table_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatefield',
            name='is_table',
            field=models.BooleanField(default=False, verbose_name='Is Table'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='line_points',
            field=models.JSONField(blank=True, null=True, verbose_name='Line Points'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='table_drawn_cells',
            field=models.JSONField(blank=True, null=True, verbose_name='Table Drawn Cells'),
        ),
        migrations.AlterField(
            model_name='templatefield',
            name='table_settings',
            field=models.JSONField(blank=True, null=True, verbose_name='Table Settings'),
        ),
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Image Name')),
                ('page', models.IntegerField(verbose_name='Page Number')),
                ('image_data', models.TextField(verbose_name='Image Data')),
                ('width', models.IntegerField(default=0, verbose_name='Width')),
                ('height', models.IntegerField(default=0, verbose_name='Height')),
                ('format', models.CharField(max_length=10, verbose_name='Format')),
                ('is_logo', models.BooleanField(default=False, verbose_name='Is Logo')),
                ('is_signature', models.BooleanField(default=False, verbose_name='Is Signature')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pdf_app.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Image',
                'verbose_name_plural': 'Template Images',
                'ordering': ['template', 'page', 'name'],
            },
        ),
    ]
