# Generated by Django 5.1.7 on 2025-03-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0012_alter_templatefield_is_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='identifier_page',
            field=models.IntegerField(default=1, verbose_name='Identifier Page'),
        ),
        migrations.AddField(
            model_name='template',
            name='unique_identifier_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Unique Identifier Text'),
        ),
    ]
