# Generated by Django 5.1.7 on 2025-03-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0013_template_identifier_page_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='field',
            unique_together={('configuration', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('configuration', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tablecolumn',
            unique_together={('table', 'name')},
        ),
    ]
