# Generated by Django 5.1.7 on 2025-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0014_alter_field_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='has_invisible_text',
            field=models.BooleanField(default=False, verbose_name='Contains Invisible Text'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_dot_matrix',
            field=models.BooleanField(default=False, verbose_name='Dot Matrix File'),
        ),
        migrations.AddField(
            model_name='template',
            name='is_encoded_text',
            field=models.BooleanField(default=False, verbose_name='Encoded Text File'),
        ),
    ]
