# Generated by Django 5.1.7 on 2025-03-31 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0015_template_has_invisible_text_template_is_dot_matrix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='has_page_numbers',
            field=models.BooleanField(default=False, verbose_name='Page Numbers Available'),
        ),
        migrations.CreateModel(
            name='TemplatePagePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('first', 'First'), ('last', 'Last'), ('custom', 'Custom')], max_length=10, verbose_name='Page Position')),
                ('delta', models.IntegerField(default=0, verbose_name='Delta Value')),
                ('page_number', models.IntegerField(blank=True, help_text='Used when position is custom', null=True, verbose_name='Page Number')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_positions', to='pdf_app.template', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Template Page Position',
                'verbose_name_plural': 'Template Page Positions',
                'ordering': ['template', 'position'],
            },
        ),
    ]
