# Generated by Django 5.1.7 on 2025-03-31 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0016_template_has_page_numbers_templatepageposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('checkbox', 'Checkbox'), ('selection', 'Selection'), ('boolean', 'Boolean')], default='text', max_length=20, verbose_name='Field Type'),
        ),
    ]
