# Generated by Django 5.1.7 on 2025-04-01 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0017_alter_field_field_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Table Name')),
                ('table_number', models.PositiveIntegerField(default=1, verbose_name='Table Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('template_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_configurations', to='pdf_app.templatefield', verbose_name='Template Field')),
            ],
            options={
                'verbose_name': 'Table Configuration',
                'verbose_name_plural': 'Table Configurations',
                'ordering': ['template_field', 'table_number'],
                'unique_together': {('template_field', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='TableColumnConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Column Name')),
                ('column_number', models.PositiveIntegerField(default=1, verbose_name='Column Number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('python_function', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='table_column_configurations', to='pdf_app.pythonfunction', verbose_name='Python Function')),
                ('table_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='column_configurations', to='pdf_app.tableconfiguration', verbose_name='Table Configuration')),
            ],
            options={
                'verbose_name': 'Table Column Configuration',
                'verbose_name_plural': 'Table Column Configurations',
                'ordering': ['table_configuration', 'column_number'],
                'unique_together': {('table_configuration', 'column_number')},
            },
        ),
    ]
