# Generated by Django 5.1.7 on 2025-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_app', '0018_tableconfiguration_tablecolumnconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableconfiguration',
            name='advanced_settings',
            field=models.JSONField(blank=True, null=True, verbose_name='Advanced Settings'),
        ),
        migrations.AddField(
            model_name='tableconfiguration',
            name='bbox_height',
            field=models.FloatField(blank=True, null=True, verbose_name='BBox Height'),
        ),
        migrations.AddField(
            model_name='tableconfiguration',
            name='bbox_width',
            field=models.FloatField(blank=True, null=True, verbose_name='BBox Width'),
        ),
        migrations.AddField(
            model_name='tableconfiguration',
            name='bbox_x',
            field=models.FloatField(blank=True, null=True, verbose_name='BBox X'),
        ),
        migrations.AddField(
            model_name='tableconfiguration',
            name='bbox_y',
            field=models.FloatField(blank=True, null=True, verbose_name='BBox Y'),
        ),
    ]
